import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import './font-awesome'; 
import { AutoConnectProvider } from "@/components/walletProvider/AutoConnectProvider";
import { WalletProvider } from "@/components/walletProvider/WalletProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AutoConnectProvider>
          <WalletProvider>
            {children}
            <Toaster />
          </WalletProvider>
        </AutoConnectProvider>
      </body>
    </html>
  );
}